### ISSUE TITLE
Crash on wrapping certain pages

### ISSUE THREAD

**Issue by makeworld-the-better-one** [makeworld-the-better-one/amfora#20]
`gemini://wp.pitr.ca/en/Gemini_(constellation)` was pasted into the bottom bar. This was the panic output:

```
Loading...                                                  panic: runtime error: slice bounds out of range [:17] with length 12                                                              

                                                                                                                                goroutine 82 [running]:
                                                                                                                                                       gitlab.com/tslocum/cview.WordWrap.func1(0xc0003b5ea8, 0xc, 0x62, 0xde3e40, 0xc)
                                                /home/makeworld/go/pkg/mod/gitlab.com/tslocum/cview@v1.4.8-0.20200614211415-f477be8ba472/util.go:487 +0x117
                                                                                                                                                           gitlab.com/tslocum/cview.WordWrap.func2(0xc0000000e1, 0x0, 0x0, 0x0, 0xd1, 0x2, 0xc5, 0x1, 0xc0001e8300)
                                                                        /home/makeworld/go/pkg/mod/gitlab.com/tslocum/cview@v1.4.8-0.20200614211415-f477be8ba472/util.go:535 +0x341
                                                                                                                                                                                   gitlab.com/tslocum/cview.iterateString(0xc00025a0f0, 0xe7, 0xc000169940, 0xffffffffffffffff)
                                                                                        /home/makeworld/go/pkg/mod/gitlab.com/tslocum/cview@v1.4.8-0.20200614211415-f477be8ba472/util.go:594 +0x187
     gitlab.com/tslocum/cview.WordWrap(0xc0003b5e46, 0xea, 0x64, 0xc000238d90, 0x1, 0x1)
                                                                                                /home/makeworld/go/pkg/mod/gitlab.com/tslocum/cview@v1.4.8-0.20200614211415-f477be8ba472/util.go:492 +0x3a2
             github.com/makeworld-the-better-one/amfora/renderer.convertRegularGemini(0xc0003b2800, 0x42a9, 0x0, 0x64, 0x0, 0x9d3f7b, 0x2, 0xc0003b2800, 0x42a9)
                                                                                                                                                                        /home/makeworld/go/src/github.com/makeworld-the-better-one/amfora/renderer/renderer.go:133 +0xc69
                                                                           github.com/makeworld-the-better-one/amfora/renderer.RenderGemini(0xc000380000, 0x4118, 0x64, 0x7e00, 0xc000380000, 0x4118, 0x0, 0x0)
                        /home/makeworld/go/src/github.com/makeworld-the-better-one/amfora/renderer/renderer.go:182 +0x6af
                                                                                                                         github.com/makeworld-the-better-one/amfora/renderer.MakePage(0xc00059f400, 0x2d, 0xc0000fa210, 0x64, 0x0, 0x0, 0x0)
                                                /home/makeworld/go/src/github.com/makeworld-the-better-one/amfora/renderer/page.go:79 +0x363
                                                                                                                                            github.com/makeworld-the-better-one/amfora/display.handleURL(0xc00024bc80, 0x2d, 0x0, 0x0, 0x0)
                                                /home/makeworld/go/src/github.com/makeworld-the-better-one/amfora/display/private.go:246 +0x289
                                                                                                                                               github.com/makeworld-the-better-one/amfora/display.URL.func1(0xc00024bc80, 0x2d)
                                        /home/makeworld/go/src/github.com/makeworld-the-better-one/amfora/display/display.go:452 +0x3f
                                                                                                                                      created by github.com/makeworld-the-better-one/amfora/display.URL
                /home/makeworld/go/src/github.com/makeworld-the-better-one/amfora/display/display.go:451 +0xe7

                                                                                                              
```

**Comment by makeworld-the-better-one** [comment]
This also occurs when loading the URL from the command line, with the same error. It only occurs after the page has loaded, it seems to be a rendering error.

**Comment by makeworld-the-better-one** [comment]
[Downloaded version of page](https://github.com/makeworld-the-better-one/amfora/files/4833372/wp-gemini.txt)

[Archived version](https://web.archive.org/web/20200625191410/https://portal.mozz.us/gemini/wp.pitr.ca/en/Gemini_%28constellation%29?raw=1)

In case it changes.

**Comment by makeworld-the-better-one** [comment]
This seems to be an issue with `cview.WordWrap`, and the escaped brackets on that page. An upstream bug should be filed. In the meantime, some sort of recover should be added around the WordWrap function, that will return and display the page content, unwrapped, but with an Info box for the user maybe.

**Comment by makeworld-the-better-one** [comment]
I've isolated the issue to this line:
```
In [Chinese astronomy], the stars that correspond to Gemini are located in two areas: the [White Tiger of the West] (西方白虎, *Xī Fāng Bái Hǔ*) and the [Vermillion Bird of the South] (南方朱雀, *Nán Fāng Zhū Què*).
```
Maybe the combination of brackets and complex Asian unicode characters?

**Comment by makeworld-the-better-one** [comment]
cview [issue 27](https://gitlab.com/tslocum/cview/-/issues/27) filed for this issue.

**Comment by makeworld-the-better-one** [comment]
> In the meantime, some sort of recover should be added around the WordWrap function

This is what was done. Loading the page above does not crash Amfora anymore. The line that was causing the issue is still displayed, just not wrapped.
