### ISSUE TITLE
Application Crashes in Bookmarks when pressing Enter key

### ISSUE THREAD

**Issue by aburd** [makeworld-the-better-one/amfora#44]
OS: OSX Mojave 10.14.6
Release: v1.2.0 amfora-darwin-amd64

## Steps to reproduce

1. run amfora
2. navigate to "bookmarks"
3. press the enter key (I don't have any bookmarks, I'm not sure if this is related)

### Error output in terminal
```
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
gitlab.com/tslocum/cview.(*Application).Run.func1(0xc00011cfc0)
	/home/makeworld/go/pkg/mod/gitlab.com/tslocum/cview@v1.4.8-0.20200614211415-f477be8ba472/application.go:268 +0x81
panic(0x1599b00, 0xc00056b9e0)
	/usr/lib/go/src/runtime/panic.go:969 +0x166
github.com/makeworld-the-better-one/amfora/display.NewTab.func2(0xc00060000d)
	/home/makeworld/go/src/github.com/makeworld-the-better-one/amfora/display/display.go:402 +0x742
gitlab.com/tslocum/cview.(*TextView).InputHandler.func1(0xc00060f7c0, 0xc00001f130)
	/home/makeworld/go/pkg/mod/gitlab.com/tslocum/cview@v1.4.8-0.20200614211415-f477be8ba472/textview.go:1177 +0x1ca
gitlab.com/tslocum/cview.(*Box).WrapInputHandler.func1(0xc00060f7c0, 0xc00001f130)
	/home/makeworld/go/pkg/mod/gitlab.com/tslocum/cview@v1.4.8-0.20200614211415-f477be8ba472/box.go:192 +0x5d
gitlab.com/tslocum/cview.(*Application).Run(0xc00011cfc0, 0x0, 0x0)
	/home/makeworld/go/pkg/mod/gitlab.com/tslocum/cview@v1.4.8-0.20200614211415-f477be8ba472/application.go:357 +0x66d
main.main()
	/home/makeworld/go/src/github.com/makeworld-the-better-one/amfora/amfora.go:42 +0x289
```

**Comment by makeworld-the-better-one** [comment]
Thanks for the bug report! This bug has been fixed in the master branch, and will be in the v1.3.0 release.

> I don't have any bookmarks, I'm not sure if this is related

It is related, this will not occur when you have a bookmark.
